In [1]:
from utils_processing.utils import *
import matplotlib.pyplot as plt
%matplotlib inline
from itertools import combinations

In [2]:
walking_files = ['Activity-Data/Samsung/Walk/Walk_N2/Walk_N2Pressure.csv', 'Activity-Data/Samsung/Walk/Walk_N_3/Walk_N_3Pressure.csv', 
                 'Activity-Data/Samsung/Walk/Walk_N/Walk_NPressure.csv', 'Activity-Data/Samsung/Walk/Walk_P1/Walk_P1Pressure.csv',
                 'Activity-Data/Samsung/Walk/Walk_P2/Walk_P2Pressure.csv']

In [3]:
climbing_files = ['Activity-Data/Samsung/Climbing_Up/Climb_Up_1/Climb_Up_1Pressure.csv', 'Activity-Data/Samsung/Climbing_Up/Climb_Up_2/Climb_Up_2Pressure.csv',    
                 'Activity-Data/Samsung/Climbing_Up/Climb_Up_3/Climb_Up_3Pressure.csv', 'Activity-Data/Samsung/Climbing_Up/Climb_Up_4/Climb_Up_4Pressure.csv',    
                 'Activity-Data/Samsung/Climbing_Up/Climb_Up_4/Climb_Up_4Pressure.csv', 'Activity-Data/Samsung/Climbing_Up/Climb_Up_6/Climb_Up_6Pressure.csv',
                 'Activity-Data/Samsung/Climbing_Up/Climb_Up_7/Climb_Up_7Pressure.csv', 'Activity-Data/Samsung/Climbing_Up/Climb_Up_8/Climb_Up_8Pressure.csv']

In [4]:
downstairs_files = ['Activity-Data/Samsung/Climbing_Down/Climb_Down_1/Climb_Down_1Pressure.csv', 'Activity-Data/Samsung/Climbing_Down/Climb_Down_2/Climb_Down_2Pressure.csv',    
                    'Activity-Data/Samsung/Climbing_Down/Climb_Down_3/Climb_Down_3Pressure.csv', 'Activity-Data/Samsung/Climbing_Down/Climb_Down_6/Climb_Down_6Pressure.csv',
                    'Activity-Data/Samsung/Climbing_Down/Climb_Down_8/Climb_Down_8Pressure.csv', 'Activity-Data/Samsung/Climbing_Down/Climb_Down_9/Climb_Down_9Pressure.csv']

In [5]:
walking_frame = read_concatenate_files(walking_files, usecols=[0,1,2])
walking_frame.head()

timestamp    pressure             UUID 
0  1511792456293  963.100830  80ec3f676e17debf
1  1511792570567  963.165527  80ec3f676e17debf
2  1511792570742  963.188232  80ec3f676e17debf
3  1511792570938  963.224121  80ec3f676e17debf
4  1511792571101  963.251953  80ec3f676e17debf

In [6]:
climbing_frame = read_concatenate_files(climbing_files + downstairs_files, usecols=[0,1,2])
climbing_frame.head()

timestamp    pressure             UUID 
0  1511793556917  963.046631  80ec3f676e17debf
1  1511794106361  963.146729  80ec3f676e17debf
2  1511794106722  963.150879  80ec3f676e17debf
3  1511794106903  963.150391  80ec3f676e17debf
4  1511794107086  963.163818  80ec3f676e17debf

In [49]:
w_windows, w_ts_windows = create_sliding_windows_by_time(walking_frame, 1, 7500)
c_windows, c_ts_windows = create_sliding_windows_by_time(climbing_frame, 1, 7500)
print(len(w_windows), len(w_ts_windows))
print(len(c_windows), len(c_ts_windows))

23 23
22 22


In [31]:
print(len(climbing_frame), len(walking_frame))

783 1505


In [32]:
print([i for i in c_ts_windows])

[[1511793556917], [1511794106361, 1511794106722, 1511794106903, 1511794107086, 1511794107260, 1511794107441, 1511794107628, 1511794107811, 1511794107985, 1511794108160, 1511794108342, 1511794108527, 1511794108700, 1511794108887, 1511794109060, 1511794109241, 1511794109427, 1511794109600, 1511794109783, 1511794109966, 1511794110140, 1511794110320, 1511794110499, 1511794110499], [1511794129396, 1511794129581, 1511794129770, 1511794129936, 1511794130116, 1511794130296, 1511794130481, 1511794130657, 1511794130838, 1511794131018, 1511794131199, 1511794131378, 1511794131556, 1511794131736, 1511794131918, 1511794132098, 1511794132276, 1511794132459, 1511794132638, 1511794132816, 1511794132997, 1511794133178, 1511794133358, 1511794133535, 1511794133719, 1511794133896, 1511794134081, 1511794134256, 1511794134436, 1511794134656, 1511794134799, 1511794134981, 1511794135162, 1511794135338, 1511794135521, 1511794135696, 1511794135876, 1511794136057, 1511794136236, 1511794136421, 1511794136597, 1511

In [50]:
walking_frame['label'] = 0
climbing_frame['label'] = 1
print(climbing_frame.tail())
print(walking_frame.tail())

        timestamp    pressure             UUID   label
38  1511795336344  962.557129  80ec3f676e17debf      1
39  1511795336519  962.565918  80ec3f676e17debf      1
40  1511795336699  962.569092  80ec3f676e17debf      1
41  1511795336881  962.568848  80ec3f676e17debf      1
42  1511795337057  962.571777  80ec3f676e17debf      1
         timestamp    pressure             UUID   label
409  1511795440689  962.785889  80ec3f676e17debf      0
410  1511795440866  962.779297  80ec3f676e17debf      0
411  1511795441049  962.778809  80ec3f676e17debf      0
412  1511795441228  962.773193  80ec3f676e17debf      0
413  1511795441405  962.750244  80ec3f676e17debf      0


In [51]:
w_iqr = compute_inter_quartile_distance_window(w_windows)
c_iqr = compute_inter_quartile_distance_window(c_windows)

In [52]:
w_std = compute_std_deviation_window(w_windows)
c_std = compute_std_deviation_window(c_windows)

In [53]:
w_derivative = compute_sum_derivative_window(w_windows, w_ts_windows)
c_derivative = compute_sum_derivative_window(c_windows, c_ts_windows)

/home/nithishr/virtual-envs/activity_recognition/lib/python3.5/site-packages/numpy/lib/function_base.py:1768: RuntimeWarning: divide by zero encountered in true_divide
  b = (dx2 - dx1) / (dx1 * dx2)
/home/nithishr/virtual-envs/activity_recognition/lib/python3.5/site-packages/numpy/lib/function_base.py:1769: RuntimeWarning: divide by zero encountered in true_divide
  c = dx1 / (dx2 * (dx1 + dx2))
/home/nithishr/virtual-envs/activity_recognition/lib/python3.5/site-packages/numpy/lib/function_base.py:1775: RuntimeWarning: invalid value encountered in add
  out[slice1] = a * f[slice2] + b * f[slice3] + c * f[slice4]
/home/nithishr/virtual-envs/activity_recognition/lib/python3.5/site-packages/numpy/lib/function_base.py:1791: RuntimeWarning: invalid value encountered in true_divide
  out[slice1] = (y[slice2] - y[slice3]) / dx_n


In [54]:
c_derivative = np.nan_to_num(c_derivative)

In [55]:
print(w_derivative, c_derivative)

[0.00029711003710627937, -0.00043243517140613506, 0.0001317626854591786, 0.00037977703111676122, -0.00015729517550134518, -0.00063078160610320708, -5.3645830156346638e-05, 0.0002378279090722241, -0.00030440212096586217, -0.0022940352155549327, -0.00022792349379659334, -0.00012888652492690968, -0.00017003811059560474, 0.00016037608382251341, 0.00054769452021062148, -0.0001445181619253925, 0.00019338515167856453, -0.00062184327168312388, 0.0002871905549961436, 3.0737300928604546e-05] [  0.00000000e+00  -1.69233372e-03   0.00000000e+00  -2.46923273e-03
  -2.09065898e-03  -2.08039317e-03  -2.08390948e-03  -1.35131656e-03
  -4.62732241e-04  -2.60368352e-03   6.14112496e-05  -1.22965956e-03
   4.64234418e-03   1.22123950e-03   0.00000000e+00   6.54162375e-04
   0.00000000e+00   1.97491039e-03]


In [56]:
print(len(w_iqr),len(c_iqr), len(w_std), len(c_std), len(w_derivative), len(c_derivative))

20 18 20 18 20 18


In [17]:
print(type(w_derivative[0]), type(w_std[1]), type(w_iqr[2]))

<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'>


In [18]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import OneHotEncoder

In [57]:
w_feature_vector = np.column_stack((np.array(w_std).reshape(-1, 1), np.array(w_derivative).reshape(-1, 1), 
                                   np.array(w_iqr).reshape(-1, 1)))
print(type(w_feature_vector), len(w_feature_vector), w_feature_vector.shape)

<class 'numpy.ndarray'> 20 (20, 3)


In [58]:
c_feature_vector = np.column_stack((np.array(c_std).reshape(-1, 1), np.array(c_derivative).reshape(-1, 1), 
                                   np.array(c_iqr).reshape(-1, 1)))
print(type(c_feature_vector), len(c_feature_vector), c_feature_vector.shape)

<class 'numpy.ndarray'> 18 (18, 3)


In [26]:
# labels_vector = np.stack((np.array([0 for i in range(len(w_feature_vector))]).reshape(-1,1), 
#                           np.array([1 for i in range(len(c_feature_vector))]).reshape(-1,1)))
# print(type(labels_vector), len(labels_vector), labels_vector.shape)

ValueError: all input arrays must have the same shape

In [27]:
# c_labels = np.array([1 for i in range(len(c_feature_vector))]).reshape(-1,1)
# print(c_labels.shape)
# w_labels = np.array([0 for i in range(len(w_feature_vector))]).reshape(-1,1)
# print(w_labels.shape)
# labels_vector = np.stack((w_labels,c_labels))
# print(type(labels_vector), len(labels_vector), labels_vector.shape)

(37, 1)
(49, 1)


ValueError: all input arrays must have the same shape

In [21]:
# print(type(w_labels[5]))

NameError: name 'w_labels' is not defined

In [59]:
c_labels = np.full((len(c_feature_vector),1), 1)
w_labels = np.full((len(w_feature_vector),1), 0)
print(c_labels.shape, w_labels.shape)

(18, 1) (20, 1)


In [60]:
labels_vector = np.concatenate((w_labels, c_labels))
print(type(labels_vector), len(labels_vector), labels_vector.shape)

<class 'numpy.ndarray'> 38 (38, 1)


In [61]:
feature_vectors = np.concatenate((w_feature_vector, c_feature_vector))
print(type(feature_vectors), len(feature_vectors), feature_vectors.shape)

<class 'numpy.ndarray'> 38 (38, 3)


In [62]:
X = np.copy(feature_vectors)
Y = np.copy(labels_vector)
Y = Y.ravel()

In [63]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

In [64]:
print(Y.shape, Y)

(38,) [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]


In [ ]:
# ohe = OneHotEncoder()
# Yt = Y.reshape(-1,1)
# print(Yt)
# Ytt = ohe.fit_transform(Yt)
# print(Ytt.shape)
# print(Ytt)

In [36]:
# print(Y,Y.reshape(-1,1))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1] [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


## Window Length = 3s

In [58]:
from sklearn.metrics import confusion_matrix
kf = KFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in kf.split(X):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[15  3]
 [ 0  0]]
83.33333333333333
[[13  4]
 [ 0  0]]
76.47058823529412
[[10  4]
 [ 1  2]]
70.58823529411765
[[ 0  0]
 [10  7]]
41.1764705882353
[[ 0  0]
 [12  5]]
29.41176470588235


In [59]:
skf = StratifiedKFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in skf.split(X,Y):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=1500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
#     print(diff)
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[8 2]
 [1 7]]
83.33333333333333
[[9 1]
 [2 6]]
83.33333333333333
[[6 4]
 [1 6]]
70.58823529411765
[[10  0]
 [ 0  7]]
100.0
[[5 4]
 [4 3]]
50.0


## Window Length = 5s

In [28]:
from sklearn.metrics import confusion_matrix
kf = KFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in kf.split(X):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[9 2]
 [0 0]]
81.81818181818181
[[10  1]
 [ 0  0]]
90.9090909090909
[[4 4]
 [0 3]]
63.63636363636363
[[0 0]
 [7 4]]
36.36363636363637
[[0 0]
 [7 3]]
30.0


In [29]:
skf = StratifiedKFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in skf.split(X,Y):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=1500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
#     print(diff)
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[6 0]
 [1 4]]
90.9090909090909
[[5 1]
 [0 5]]
90.9090909090909
[[5 1]
 [1 4]]
81.81818181818181
[[6 0]
 [1 4]]
90.9090909090909
[[4 2]
 [2 2]]
60.0


## Window Length = 10s

In [47]:
from sklearn.metrics import confusion_matrix
kf = KFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in kf.split(X):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[6]]
100.0
[[5 1]
 [0 0]]
83.33333333333333
[[2 2]
 [0 2]]
66.66666666666667
[[0 0]
 [2 4]]
66.66666666666667
[[0 0]
 [3 3]]
50.0


In [48]:
skf = StratifiedKFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in skf.split(X,Y):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=1500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
#     print(diff)
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[4 0]
 [1 2]]
85.71428571428571
[[3 0]
 [0 3]]
100.0
[[2 1]
 [1 2]]
66.66666666666667
[[3 0]
 [1 2]]
83.33333333333333
[[1 2]
 [0 2]]
60.0


## Window length = 7.5

In [65]:
from sklearn.metrics import confusion_matrix
kf = KFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in kf.split(X):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[7 1]
 [0 0]]
87.5
[[6 2]
 [0 0]]
75.0
[[2 2]
 [1 3]]
62.5
[[0 0]
 [3 4]]
57.142857142857146
[[0 0]
 [5 2]]
28.571428571428573


In [66]:
skf = StratifiedKFold(n_splits=5)
# print(list(kf.split(X)))
# print(list(kf.split(Y)))
for train, test in skf.split(X,Y):
    XTrain, XTest, YTrain, YTest = X[train], X[test], Y[train], Y[test]
    clf = RandomForestClassifier(n_estimators=1500, random_state=seed)
    clf = clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
#     print(diff)
    print(confusion_matrix(YTest, YPred))
    score = diff[diff == 0].size
    print((100.0 * score)/(YPred.size))

[[4 0]
 [1 3]]
87.5
[[3 1]
 [1 3]]
75.0
[[3 1]
 [2 2]]
62.5
[[4 0]
 [0 3]]
100.0
[[3 1]
 [3 0]]
42.857142857142854
