In [1]:
import numpy as np
import os

In [28]:
XTrain = np.loadtxt('ActivityLog.csv', delimiter=',', dtype='str')

In [29]:
XTrain.shape

(1171, 25)

In [30]:
XTrain = XTrain[28:]

In [31]:
XTrain.shape

(1143, 25)

In [32]:
XTrain[:5]

array([['-0.670082734', '-0.670025414', '-0.792625194', '-0.94234768',
        '-2.045734651', '-1.870624671', '-2.466389799', '-0.800681604',
        '-0.410635809', '0.68467463', '0.430518847', '0.089264115',
        '-0.399635138', '-0.766293883', '-1.043289532', '-0.769320455',
        '-0.397893954', '0.855069631', '-0.10460162', '-0.300502041',
        '-0.828248297', '0.20641181', '-0.73878926', '-0.00519707', '3'],
       ['-0.861629091', '-1.067786329', '-1.004662542', '-1.192019706',
        '-1.691731914', '-1.873449733', '-2.483530608', '-1.100105432',
        '-0.33402968', '0.660998979', '0.204621014', '0.145373889',
        '-0.447505849', '-1.196392244', '-1.196684941', '-0.899659644',
        '-1.194254625', '-0.134052804', '-0.158409253', '-0.321210473',
        '-1.284549258', '0.388558613', '-0.727133125', '-0.028941119', '3'],
       ['-1.120216684', '-1.243872472', '-1.088129179', '-1.321977776',
        '-1.568389836', '-1.84344819', '-2.466832437', '-1.230669109

In [33]:
YTrain = XTrain[:,-1]
YTrain = YTrain.astype(np.float)

In [34]:
print(YTrain.shape, YTrain[:5])

(1143,) [ 3.  3.  3.  3.  3.]


In [35]:
XTrain = XTrain[:,:-1]
print(XTrain.shape)

(1143, 24)


In [36]:
print(XTrain[:5])

[['-0.670082734' '-0.670025414' '-0.792625194' '-0.94234768' '-2.045734651'
  '-1.870624671' '-2.466389799' '-0.800681604' '-0.410635809' '0.68467463'
  '0.430518847' '0.089264115' '-0.399635138' '-0.766293883' '-1.043289532'
  '-0.769320455' '-0.397893954' '0.855069631' '-0.10460162' '-0.300502041'
  '-0.828248297' '0.20641181' '-0.73878926' '-0.00519707']
 ['-0.861629091' '-1.067786329' '-1.004662542' '-1.192019706'
  '-1.691731914' '-1.873449733' '-2.483530608' '-1.100105432' '-0.33402968'
  '0.660998979' '0.204621014' '0.145373889' '-0.447505849' '-1.196392244'
  '-1.196684941' '-0.899659644' '-1.194254625' '-0.134052804'
  '-0.158409253' '-0.321210473' '-1.284549258' '0.388558613' '-0.727133125'
  '-0.028941119']
 ['-1.120216684' '-1.243872472' '-1.088129179' '-1.321977776'
  '-1.568389836' '-1.84344819' '-2.466832437' '-1.230669109' '-0.312126644'
  '0.660937209' '0.20757578' '0.058901833' '-0.769545176' '-1.247878471'
  '-1.2653933' '-1.060588654' '-1.274839619' '-0.126441017' '

In [37]:
XTrain = XTrain.astype(np.float)
print(XTrain.shape)
print(XTrain[:4])

(1143, 24)
[[-0.67008273 -0.67002541 -0.79262519 -0.94234768 -2.04573465 -1.87062467
  -2.4663898  -0.8006816  -0.41063581  0.68467463  0.43051885  0.08926412
  -0.39963514 -0.76629388 -1.04328953 -0.76932046 -0.39789395  0.85506963
  -0.10460162 -0.30050204 -0.8282483   0.20641181 -0.73878926 -0.00519707]
 [-0.86162909 -1.06778633 -1.00466254 -1.19201971 -1.69173191 -1.87344973
  -2.48353061 -1.10010543 -0.33402968  0.66099898  0.20462101  0.14537389
  -0.44750585 -1.19639224 -1.19668494 -0.89965964 -1.19425462 -0.1340528
  -0.15840925 -0.32121047 -1.28454926  0.38855861 -0.72713313 -0.02894112]
 [-1.12021668 -1.24387247 -1.08812918 -1.32197778 -1.56838984 -1.84344819
  -2.46683244 -1.23066911 -0.31212664  0.66093721  0.20757578  0.05890183
  -0.76954518 -1.24787847 -1.2653933  -1.06058865 -1.27483962 -0.12644102
  -0.20758273 -0.25653851 -1.37904917  0.37466526 -0.73167366 -0.02914659]
 [-1.14894864 -1.27578449 -1.09849772 -1.33402825 -1.57045347 -1.81226997
  -2.46548721 -1.21721264

In [11]:
#Multi Class SVM
from sklearn import svm
def classifyMultiClassSVMClassifier(XTrain, XTest, YTrain, YTest, params):
    ker = params['kernel']
    YPred = svm.SVC(kernel=ker).fit(XTrain, YTrain).predict(XTest)
    diff = YPred - YTest
    score = diff[diff == 0].size
    return (100.0 * score)/(YPred.size)

In [39]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
# def classifyRandomForestClassifier(XTrain, XTest, YTrain, YTest,trees=100,crit='gini'):
def classifyRandomForestClassifier(XTrain, XTest, YTrain, YTest, params):
    trees = params['trees']
    crit = params['criterion']
    clf = RandomForestClassifier(n_estimators=trees,criterion=crit)
    clf.fit(XTrain, YTrain)
    YPred = clf.predict(XTest)
    diff = YPred - YTest
    score = diff[diff == 0].size
    return (100.0 * score)/(YPred.size)

In [40]:
#K Nearest Neighbours Classifier
from sklearn.neighbors import KNeighborsClassifier
def classifyKNNClassifier(XTrain, XTest, YTrain, YTest, params):
    neighbours = params['neighbours']
    neigh = KNeighborsClassifier(n_neighbors=neighbours)
    YPred = neigh.fit(XTrain, YTrain).predict(XTest)
    diff = YPred - YTest
    score = diff[diff == 0].size
    return (100.0 * score)/(YPred.size)

In [12]:
from sklearn.cross_validation import StratifiedKFold
def stratifiedKFoldVal(XTrain, YTrain, classify, params):
    n_folds = 5
    score = 0.0
    skf = StratifiedKFold(YTrain, n_folds)
    for train_index, test_index in skf:
        X_train, X_test = XTrain[train_index], XTrain[test_index]
        y_train, y_test = YTrain[train_index], YTrain[test_index]
        score += classify(X_train, X_test,  y_train, y_test, params)
    return score/n_folds

/home/nithishr/virtual_envs/activity_detection/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [13]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(YTrain)

ValueError: could not convert string to float: 'elevator_down'

In [14]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(YTrain)
print(lb.classes_)

['Turning arround' 'Walking' 'elevator_down' 'elevator_up' 'sitting'
 'standing' 'walking' 'walking_downstairs' 'walking_upstairs']


In [16]:
YTrainOHE = lb.transform(YTrain)

In [17]:
YTrainOHE.shape

(1143, 9)

In [20]:
print(YTrainOHE[:5])

[[0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


In [38]:
params = {'kernel':'linear'}
score = stratifiedKFoldVal(XTrain, YTrain, classifyMultiClassSVMClassifier, params)
print(score)

72.75828175005157


In [42]:
params = {'trees':200, 'criterion':'entropy'}
score = stratifiedKFoldVal(XTrain, YTrain, classifyRandomForestClassifier, params)
print(score)

84.67034859354649


In [43]:
selectNeighbourScores = []

params = {'neighbours':2}
score = stratifiedKFoldVal(XTrain, YTrain, classifyKNNClassifier, params)
# print score
selectNeighbourScores.append(score)

params = {'neighbours':3}
score = stratifiedKFoldVal(XTrain, YTrain, classifyKNNClassifier, params)
# print score
selectNeighbourScores.append(score)

params = {'neighbours':4}
score = stratifiedKFoldVal(XTrain, YTrain, classifyKNNClassifier, params)
# print score
selectNeighbourScores.append(score)

params = {'neighbours':5}
score = stratifiedKFoldVal(XTrain, YTrain, classifyKNNClassifier, params)
# print score
selectNeighbourScores.append(score)

params = {'neighbours':10}
score = stratifiedKFoldVal(XTrain, YTrain, classifyKNNClassifier, params)
# print score
selectNeighbourScores.append(score)

print(selectNeighbourScores)

[67.40372437081258, 68.1684428586681, 67.74167995828665, 69.496612960855, 69.74564297250147]


In [24]:
XTrain1 = XTrain[:859]
XTest1 = XTrain[859:]
YTrain1 = YTrainOHE[:859]
YTest1 = YTrainOHE[859:]
print(XTrain1.shape, XTest1.shape, YTrain1.shape, YTest1.shape)

(859, 24) (284, 24) (859, 9) (284, 9)


In [23]:
YPred = svm.SVC(kernel='linear').fit(XTrain1, YTrain1).predict(XTest1)

ValueError: bad input shape (859, 9)

In [26]:
print(type(XTrain1))
print(type(YTrain1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [27]:
from sklearn.feature_extraction import DictVectorizer
v = DictVectorizer(sparse=False)
YTrain_Test = {'Turning arround' 'Walking' 'elevator_down' 'elevator_up' 'sitting'
 'standing' 'walking' 'walking_downstairs' 'walking_upstairs']
Y = v.fit_transform(
print(Y, Y.shape)

AttributeError: 'numpy.str_' object has no attribute 'items'